/*
 * Copyright (c) 2020 · Marton Lederer
 * This file was created / generated by Marton Lederer
 * See the LICENSE on the github repo
 * https://github.com/MartonDev
 * https://marton.lederer.hu
 */

import { Image, RGB } from './Image.ts'

/*
*
* Creating a PNG image
*
*/
export class PNGImage extends Image {

  constructor (width: number, height: number, depth: number = 10, backgroundColor: RGB = { r: 0, g: 0, b: 0, a: 0 }) {

    super(width, height, depth, backgroundColor, '\x89PNG\r\n\x1A\n')

  }

}